name: iOS Unsigned Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS unsigned
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          mkdir Payload
          cp -R build/ios/iphoneos/Runner.app Payload
          zip -r unsigned_app.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IOS-Unsigned-App
          path: unsigned_app.ipa
